/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import controller.ControllerLogin;

import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import model.Request;
import model.Subject;
import model.Titulation;

/**
 *
 * @author inftel12
 */
public class JF_ViewSchedule extends javax.swing.JFrame {

    /**
     * Creates new form JF_ViewSchedule
     * 
     */
    String titulo[] ={"Titulación", "Curso","Cuatrimestre","Asignatura","Día","Hora","Aula"};
    DefaultTableModel tableJSchedule = new DefaultTableModel(null,titulo);
    public JF_ViewSchedule() {
        InputMap map = new InputMap();
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false), "pressed");
        map.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true), "released");    
        
        initComponents();       
        
        jButtonLogout.setToolTipText("Cerrar sesión");
        fillTreeSchedule();
    }
    
    private void fillTreeSchedule(){
        DefaultTreeModel model = (DefaultTreeModel) jTreeLeftPanel.getModel();
        Controller controller = new Controller();
        
        ArrayList<Titulation> titulations = controller.getTitulationsAndSubjects();
        
        for (Titulation titulation : titulations) {            
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
            root.add(new DefaultMutableTreeNode(titulation.getName()));
            int id_titulation = titulation.getId_titulation();
            
            root = root.getNextNode();
            ArrayList<String> courses = controller.getCoursesTitulationUser(id_titulation);
            for (String course : courses) {
                root.add(new DefaultMutableTreeNode(course));
                
                root = root.getNextNode();
                ArrayList<String> quarters = controller.getQuartersTitulationUser(id_titulation, course);
                
                for (String quarter : quarters) {
                    root.add(new DefaultMutableTreeNode(quarter));
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLeft = new javax.swing.JPanel();
        jSeparatorLeftPanel = new javax.swing.JSeparator();
        jPanelMenu = new javax.swing.JPanel();
        jScrollPaneLeftPanel = new javax.swing.JScrollPane();
        jTreeLeftPanel = new javax.swing.JTree();
        jLabelLogoImg = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelRTop = new javax.swing.JPanel();
        jLabelWelcomeTitle = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jPanelRTab = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPaneViewSchedule = new javax.swing.JScrollPane();
        jTableSchedule = new javax.swing.JTable();
        jPanelMakeSchedule = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jComboBoxTit = new javax.swing.JComboBox();
        jComboBoxCourse = new javax.swing.JComboBox();
        jComboBoxQuarter = new javax.swing.JComboBox();
        jComboBoxSubject = new javax.swing.JComboBox();
        jComboBoxDay = new javax.swing.JComboBox();
        jComboBoxHour = new javax.swing.JComboBox();
        jComboBoxClassroom = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablesSetSchedule = new javax.swing.JTable();
        jPanelUpdateSchedule = new javax.swing.JPanel();
        jPanelSendRequest = new javax.swing.JPanel();
        jLabelSubject = new javax.swing.JLabel();
        jTextFieldReqSubj = new javax.swing.JTextField();
        jLabelReqText = new javax.swing.JLabel();
        jLabelRequest = new javax.swing.JLabel();
        jButtonSendRequest = new javax.swing.JButton();
        jLabelReqSend = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaResq = new javax.swing.JTextArea();
        jPanelViewRequest = new javax.swing.JPanel();
        jScrollPanelViewRequest = new javax.swing.JScrollPane();
        jTableRequests = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneMessageRequest = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setName("jf_view_schedule"); // NOI18N

        jPanelLeft.setBackground(new java.awt.Color(255, 255, 255));

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        jTreeLeftPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTreeLeftPanel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Titulación");
        jTreeLeftPanel.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeLeftPanel.setCellRenderer(null);
        jScrollPaneLeftPanel.setViewportView(jTreeLeftPanel);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneLeftPanel)
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(jScrollPaneLeftPanel)
                .addContainerGap())
        );

        jLabelLogoImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/master_inftel.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogoImg, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jSeparatorLeftPanel))
                .addContainerGap())
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelRight.setBackground(new java.awt.Color(255, 255, 255));

        jPanelRTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRTop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelWelcomeTitle.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabelWelcomeTitle.setText("GESTOR DE HORARIOS UMA - BIENVENIDO/A (Usuario)");

        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logout2.jpg"))); // NOI18N
        jButtonLogout.setBorderPainted(false);
        jButtonLogout.setMaximumSize(new java.awt.Dimension(31, 31));
        jButtonLogout.setMinimumSize(new java.awt.Dimension(31, 31));
        jButtonLogout.setPreferredSize(new java.awt.Dimension(31, 31));
        jButtonLogout.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/logout.jpg"))); // NOI18N
        jButtonLogout.setRequestFocusEnabled(false);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRTopLayout = new javax.swing.GroupLayout(jPanelRTop);
        jPanelRTop.setLayout(jPanelRTopLayout);
        jPanelRTopLayout.setHorizontalGroup(
            jPanelRTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanelRTopLayout.setVerticalGroup(
            jPanelRTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWelcomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanelRTab.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPaneMousePressed(evt);
            }
        });

        jTableSchedule.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8:30", null, null, null, null, null},
                {"9:30", null, null, null, null, null},
                {"10:30", null, null, null, null, null},
                {"11:30", null, null, null, null, null},
                {"12:30", null, null, null, null, null},
                {"13:30", null, null, null, null, null},
                {"15:30", null, null, null, null, null},
                {"16:30", null, null, null, null, null},
                {"17:30", null, null, null, null, null},
                {"18:30", null, null, null, null, null},
                {"19:30", null, null, null, null, null},
                {"20:30", null, null, null, null, null}
            },
            new String [] {
                "Hora/Día", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes"
            }
        ));
        jTableSchedule.setMinimumSize(new java.awt.Dimension(90, 300));
        jTableSchedule.setRowHeight(40);
        jScrollPaneViewSchedule.setViewportView(jTableSchedule);

        jTabbedPane.addTab("Horario", jScrollPaneViewSchedule);

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jComboBoxTit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxTit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titulación" }));
        jComboBoxTit.setToolTipText("Titulación");
        jComboBoxTit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTitItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBoxTit);

        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Curso" }));
        jComboBoxCourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCourseItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBoxCourse);

        jComboBoxQuarter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cuatrimestre" }));
        jComboBoxQuarter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxQuarterItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBoxQuarter);

        jComboBoxSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asignatura" }));
        jComboBoxSubject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSubjectItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBoxSubject);

        jComboBoxDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Día" }));
        jComboBoxDay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDayItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBoxDay);

        jComboBoxHour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hora" }));
        jComboBoxHour.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxHourItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBoxHour);

        jComboBoxClassroom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aula" }));
        jToolBar1.add(jComboBoxClassroom);

        jButton1.setText("Añadir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);

        jTablesSetSchedule.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTablesSetSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulación", "Curso", "Cuatrimestre", "Asignatura", "Día", "Hora", "Aula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablesSetSchedule);
        if (jTablesSetSchedule.getColumnModel().getColumnCount() > 0) {
            jTablesSetSchedule.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMakeScheduleLayout = new javax.swing.GroupLayout(jPanelMakeSchedule);
        jPanelMakeSchedule.setLayout(jPanelMakeScheduleLayout);
        jPanelMakeScheduleLayout.setHorizontalGroup(
            jPanelMakeScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
            .addGroup(jPanelMakeScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMakeScheduleLayout.setVerticalGroup(
            jPanelMakeScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMakeScheduleLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Crear Horario", jPanelMakeSchedule);

        javax.swing.GroupLayout jPanelUpdateScheduleLayout = new javax.swing.GroupLayout(jPanelUpdateSchedule);
        jPanelUpdateSchedule.setLayout(jPanelUpdateScheduleLayout);
        jPanelUpdateScheduleLayout.setHorizontalGroup(
            jPanelUpdateScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        jPanelUpdateScheduleLayout.setVerticalGroup(
            jPanelUpdateScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Modificar Horario", jPanelUpdateSchedule);

        jPanelSendRequest.setToolTipText("");

        jLabelSubject.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelSubject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSubject.setText(" Asunto");

        jTextFieldReqSubj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldReqSubj.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabelReqText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelRequest.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelRequest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRequest.setText(" Solicitud");

        jButtonSendRequest.setText("Enviar Solicitud");
        jButtonSendRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSendRequestMouseClicked(evt);
            }
        });

        jLabelReqSend.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelReqSend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextAreaResq.setColumns(20);
        jTextAreaResq.setRows(5);
        jScrollPane3.setViewportView(jTextAreaResq);

        javax.swing.GroupLayout jPanelSendRequestLayout = new javax.swing.GroupLayout(jPanelSendRequest);
        jPanelSendRequest.setLayout(jPanelSendRequestLayout);
        jPanelSendRequestLayout.setHorizontalGroup(
            jPanelSendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSendRequestLayout.createSequentialGroup()
                .addGroup(jPanelSendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSendRequestLayout.createSequentialGroup()
                        .addGap(633, 633, 633)
                        .addComponent(jLabelReqText, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addGroup(jPanelSendRequestLayout.createSequentialGroup()
                        .addGroup(jPanelSendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSendRequestLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanelSendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldReqSubj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelSendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabelRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                                        .addComponent(jLabelSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSendRequestLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelSendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSendRequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelReqSend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSendRequestLayout.setVerticalGroup(
            jPanelSendRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSendRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldReqSubj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRequest)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabelReqSend, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReqText)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Enviar solicitud", jPanelSendRequest);

        jTableRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Asunto", "Estado"
            }
        ));
        jTableRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableRequestsMousePressed(evt);
            }
        });
        jScrollPanelViewRequest.setViewportView(jTableRequests);

        jScrollPane1.setViewportView(jTextPaneMessageRequest);

        javax.swing.GroupLayout jPanelViewRequestLayout = new javax.swing.GroupLayout(jPanelViewRequest);
        jPanelViewRequest.setLayout(jPanelViewRequestLayout);
        jPanelViewRequestLayout.setHorizontalGroup(
            jPanelViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelViewRequestLayout.createSequentialGroup()
                .addComponent(jScrollPanelViewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );
        jPanelViewRequestLayout.setVerticalGroup(
            jPanelViewRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanelViewRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        jTabbedPane.addTab("Ver solicitudes", jPanelViewRequest);

        javax.swing.GroupLayout jPanelRTabLayout = new javax.swing.GroupLayout(jPanelRTab);
        jPanelRTab.setLayout(jPanelRTabLayout);
        jPanelRTabLayout.setHorizontalGroup(
            jPanelRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        jPanelRTabLayout.setVerticalGroup(
            jPanelRTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("Horario");

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRightLayout.createSequentialGroup()
                .addComponent(jPanelRTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        ControllerLogin controller = new ControllerLogin();
        controller.closeSession(this);
        
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jTableRequestsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRequestsMousePressed
        Controller controllerRequest = new Controller();
        int row = jTableRequests.getSelectedRow();
        String message = controllerRequest.getSelectedRequest(row);
        jTextPaneMessageRequest.setText(message);
    }//GEN-LAST:event_jTableRequestsMousePressed

    private void jTabbedPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMousePressed
        //Para ver solicitudes
        Controller controllerRequest = new Controller();
        ArrayList<Request> request = controllerRequest.getAllRequest(); 
        String titulo[] ={"Asunto", "Estado"};
        DefaultTableModel m = new DefaultTableModel(null,titulo);
        String fila[] = new String[2];

        for(Request o: request){
            fila[0]=o.getSubject();
            fila[1]=o.getState();
            m.addRow(fila);
        }
        jTableRequests.setModel(m);
        
        
        //Para crea horario
        Controller controller = new Controller();
        ArrayList<Titulation> titList = controller.getAllTitulations();
        
        Vector comboBoxItems = new Vector();
        
        comboBoxItems.add("Titulación");
        for (Titulation tit : titList) {
            comboBoxItems.add(tit.getName());
        }
        
        final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
        jComboBoxTit.setModel(model);
    }//GEN-LAST:event_jTabbedPaneMousePressed

    private void jComboBoxTitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTitItemStateChanged
        Vector comboBoxItemsCourse = new Vector();
        Vector comboBoxItemsSubject = new Vector();
        Vector comboBoxItemsQuarter = new Vector();
        Vector comboBoxItemsDay = new Vector();
        Vector comboBoxItemsHour = new Vector();
        Vector comboBoxItemsClass = new Vector();
        
        if(jComboBoxTit.getSelectedIndex()!=0){  
            comboBoxItemsCourse.add("Curso");
            comboBoxItemsCourse.add("1º");
            comboBoxItemsCourse.add("2º");
            comboBoxItemsCourse.add("3º");
            comboBoxItemsCourse.add("4º");
        }else{
            comboBoxItemsCourse.add("Curso");
            comboBoxItemsSubject.add("Asignaturas");
            final DefaultComboBoxModel modelSubject = new DefaultComboBoxModel(comboBoxItemsSubject);
            jComboBoxSubject.setModel(modelSubject);
            comboBoxItemsQuarter.add("Cuatrimestre");
            final DefaultComboBoxModel modelQuarter = new DefaultComboBoxModel(comboBoxItemsQuarter);
            jComboBoxQuarter.setModel(modelQuarter);
            comboBoxItemsDay.add("Día");
            final DefaultComboBoxModel modelDay = new DefaultComboBoxModel(comboBoxItemsDay);
            jComboBoxDay.setModel(modelDay);
            comboBoxItemsHour.add("Hora");
            final DefaultComboBoxModel modelHour = new DefaultComboBoxModel(comboBoxItemsHour);
            jComboBoxHour.setModel(modelHour);
            comboBoxItemsClass.add("Aula");
            final DefaultComboBoxModel modelClass = new DefaultComboBoxModel(comboBoxItemsClass);
            jComboBoxClassroom.setModel(modelClass);
        }
        
        final DefaultComboBoxModel modelCourse = new DefaultComboBoxModel(comboBoxItemsCourse);
        jComboBoxCourse.setModel(modelCourse);  
    }//GEN-LAST:event_jComboBoxTitItemStateChanged

    private void jComboBoxCourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCourseItemStateChanged
        Vector comboBoxItemsQuarter = new Vector();
        
        if(jComboBoxTit.getSelectedIndex()!=0){  
            comboBoxItemsQuarter.add("Cuatrimestre");
            comboBoxItemsQuarter.add("Primero");
            comboBoxItemsQuarter.add("Segundo");
        }else{
            comboBoxItemsQuarter.add(null);
        }
        
        final DefaultComboBoxModel modelQuarter = new DefaultComboBoxModel(comboBoxItemsQuarter);
        jComboBoxQuarter.setModel(modelQuarter);
    }//GEN-LAST:event_jComboBoxCourseItemStateChanged

    private void jComboBoxQuarterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxQuarterItemStateChanged
        Controller controller = new Controller();
        String titulation = (String) jComboBoxTit.getSelectedItem();
        String course = (String) jComboBoxCourse.getSelectedItem();
        String quarter = (String) jComboBoxQuarter.getSelectedItem();
        ArrayList<Subject> subList = controller.getSubjectsTitulation(titulation, course, quarter);
        
        Vector comboBoxItems = new Vector();
        
        if((jComboBoxTit.getSelectedIndex()!=0)){
            comboBoxItems.add("Asignatura");
            for (Subject subject : subList) {
                comboBoxItems.add(subject.getName());
            }
        }else{
                comboBoxItems.add("Asignatura");
        }
        final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
        jComboBoxSubject.setModel(model);
        
    }//GEN-LAST:event_jComboBoxQuarterItemStateChanged

    private void jComboBoxSubjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSubjectItemStateChanged
        Vector comboBoxItemsDay = new Vector();
        Controller controller = new Controller();
        ArrayList<String> days = controller.getAvailableDays(); 
        System.out.println(days);
        
        comboBoxItemsDay.add("Día");
        for (String day : days) {
            comboBoxItemsDay.add(day);
        }

        final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItemsDay);
        jComboBoxDay.setModel(model);
    }//GEN-LAST:event_jComboBoxSubjectItemStateChanged

    private void jComboBoxDayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDayItemStateChanged
        Controller controller = new Controller();
        Vector comboBoxItemsHour = new Vector();
        String day = (String) jComboBoxDay.getSelectedItem();
        ArrayList<String> hours = controller.getAvailableHours(day);
         
        comboBoxItemsHour.add("Hora");
        for (String hour : hours) {
            comboBoxItemsHour.add(hour);
        }

        final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItemsHour);
        jComboBoxHour.setModel(model);
    }//GEN-LAST:event_jComboBoxDayItemStateChanged

    private void jComboBoxHourItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxHourItemStateChanged
        Controller controller = new Controller();
        Vector comboBoxItemsClass = new Vector();
        String day = (String) jComboBoxDay.getSelectedItem();
        String hour = (String) jComboBoxHour.getSelectedItem();
        ArrayList<String> classroom = controller.getAvailableClassroom(day,hour);
        
        comboBoxItemsClass.add("Aula");
        for (String classfree : classroom) {
            comboBoxItemsClass.add(classfree);
        }

        final DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItemsClass);
        jComboBoxClassroom.setModel(model);
        
    }//GEN-LAST:event_jComboBoxHourItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       Controller controller = new Controller(); 
       String titulation = (String) jComboBoxTit.getSelectedItem();
       String course = (String) jComboBoxCourse.getSelectedItem();
       String quarter = (String) jComboBoxQuarter.getSelectedItem();
       String subject = (String) jComboBoxSubject.getSelectedItem();
       String day = (String) jComboBoxDay.getSelectedItem();
       String hour = (String) jComboBoxHour.getSelectedItem();
       String classroom = (String) jComboBoxClassroom.getSelectedItem(); 
       controller.setSchedule(titulation,course,quarter,subject,day,hour,classroom);
       
       String titulo[] ={"Titulación", "Curso","Cuatrimestre","Asignatura","Día","Hora","Aula"};
       String fila[] ={titulation,course,quarter,subject,day,hour,classroom};
//       DefaultTableModel m = new DefaultTableModel(null,titulo);
       
       
        tableJSchedule.addRow(fila);
   
        jTablesSetSchedule.setModel(tableJSchedule);
       
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonSendRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSendRequestMouseClicked
        // Enviar solicitud
        Controller controllerRequest = new Controller();
        boolean ok;
        ok = controllerRequest.setRequest(jTextFieldReqSubj.getText(), jTextAreaResq.getText());
        if (ok){
            jLabelReqSend.setText("Solicitud enviada correctamente"); 
        }else{
            jLabelReqSend.setText("Error al enviar solicitud");
        }
    }//GEN-LAST:event_jButtonSendRequestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_ViewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_ViewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_ViewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_ViewSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_ViewSchedule().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSendRequest;
    private javax.swing.JComboBox jComboBoxClassroom;
    private javax.swing.JComboBox jComboBoxCourse;
    private javax.swing.JComboBox jComboBoxDay;
    private javax.swing.JComboBox jComboBoxHour;
    private javax.swing.JComboBox jComboBoxQuarter;
    private javax.swing.JComboBox jComboBoxSubject;
    private javax.swing.JComboBox jComboBoxTit;
    private javax.swing.JLabel jLabelLogoImg;
    private javax.swing.JLabel jLabelReqSend;
    private javax.swing.JLabel jLabelReqText;
    private javax.swing.JLabel jLabelRequest;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelWelcomeTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelMakeSchedule;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelRTab;
    private javax.swing.JPanel jPanelRTop;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelSendRequest;
    private javax.swing.JPanel jPanelUpdateSchedule;
    private javax.swing.JPanel jPanelViewRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneLeftPanel;
    private javax.swing.JScrollPane jScrollPaneViewSchedule;
    private javax.swing.JScrollPane jScrollPanelViewRequest;
    private javax.swing.JSeparator jSeparatorLeftPanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableRequests;
    private javax.swing.JTable jTableSchedule;
    private javax.swing.JTable jTablesSetSchedule;
    private javax.swing.JTextArea jTextAreaResq;
    private javax.swing.JTextField jTextFieldReqSubj;
    private javax.swing.JTextPane jTextPaneMessageRequest;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTreeLeftPanel;
    // End of variables declaration//GEN-END:variables
}
